### ISSUE TITLE
Imagenet100 dataset load

### ISSUE THREAD

**Issue by WeiLeZhang** [G-U-N/ECCV22-FOSTER#11]
Thank you for such a good work. May I ask if I want to run some experiments on imagenet100, is the path of the imagenet1K dataset entered here in the `data.py` file?
![image](https://user-images.githubusercontent.com/103939997/207767647-28e58ce2-d879-4bd2-9b1f-085090477d80.png)

**Comment by G-U-N** [comment]
Thank you for your interest!

To run experiments on Benchmark ImageNet-100, you should manually copy the data of 100 subcategories (provided as `imagenet-sub` in the repo) into an additional folder and then specify the path to the folder in `data.py`.

Hope this clarifies your queries.

**Comment by WeiLeZhang** [comment]
OK, Thank you!
