### ISSUE TITLE
NameError: name 'cdist' is not defined

### ISSUE THREAD

**Issue by NiccoBiondi** [G-U-N/ECCV22-FOSTER#2]
Hi, 

thank you for the repo and paper. It is a really great work! 

Unfortunately, I tried to run your repo but I received a `NameError: name 'cdist' is not defined` in `ECCV22-FOSTER/models/base.py", line 132, in _eval_nme`.

I simply fixed the error adding the following import at the beginning the file [models/base.py](https://github.com/G-U-N/ECCV22-FOSTER/blob/master/models/base.py) 

```py
from scipy.spatial.distance import cdist
```

I opened this issue to improve the repo. Probably you simply missed it 😉

Best, 
Niccolò

**Comment by G-U-N** [comment]
Thank you so much for your attention and help!👍 I think I deleted this line by mistake when deleting my code comments.
