### ISSUE TITLE
How to train B0 Setting

### ISSUE THREAD

**Issue by pgh2874** [G-U-N/ECCV22-FOSTER#3]
Hi,

thank you for the code and awesome paper !!

i would like to train using B0 Cifar-100 setting

amending init_cls from 10 to 0 in cifar100.json file isn't work 

could you tell me how to train it??

I'd greatly appreciate any help you can offer.

**Comment by G-U-N** [comment]
Thanks for your interest! 
Say you want to run the `B0 inc10` setting, set both the `init_cls`  and the `increment` to 10. The same for the other B0 settings.
Simply put, the task flow `0,10, 10,..., 10` is equivalent to the `10, 10,..., 10`.

**Comment by G-U-N** [comment]
Do not forget to set the `fixed memory` to `false` in the config JSON file.
