### ISSUE TITLE
The CNN top1 curve in experiment

### ISSUE THREAD

**Issue by zhl98** [G-U-N/ECCV22-FOSTER#6]
Hi!
First of all, thank you very much for your repo. I am very interested in your paper.
I find the darknet eval is the top1 acc of the snet. However, its precision is not the same as that in the last list. Later, I found that the model used the original teacher network with two backbone networks when evaluating.
Because you update the self._network is in the begin of incremental_train().
This is the original plan to use the result of  the teacher model, or is it a mistake.
![image](https://user-images.githubusercontent.com/51871747/199687177-7c6b4188-aa2d-417b-aac8-2690f30ba077.png)

**Comment by G-U-N** [comment]
Thank you very much for pointing this out, and you should use the accuracy in darknet eval as the result of the single-backbone model. If you hope to directly get those accuracy-lists of the single-backbone model, please add the following code
```python
self._network = self._snet 
``` 
in line 133, foster.py.

Hope this clarifies your queries.
