### ISSUE TITLE
foster-cifar100.json 与 foster-rmm.json区别

### ISSUE THREAD

**Issue by wusuoweima** [G-U-N/ECCV22-FOSTER#8]
想和您做对比实验，下面这两个有什么区别啊，哪个对应论文里的算法啊，谢谢
`Train CIFAR-100
python main.py --config=foster-cifar100.json

Train FOSTER-RMM
python main.py --config=foster-rmm.json`

**Comment by G-U-N** [comment]
您好，感谢您的关注。

请使用第一个作为标准的对比。

第二个为使用RMM调整了新旧范例划分策略的性能。

**Comment by wusuoweima** [comment]
好的 非常感谢

**Comment by wusuoweima** [comment]
方便加个微信吗？想请教些其他问题
vx:wusuowei_m
